server:
  port: 5000
  management:
    endpoints:
      shutdown:
        enabled: true

spring:
  thymeleaf:
    cache: false
  datasource:
    jdbc-url: jdbc:postgresql://snippets.com233sow277.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: connectaws
    pool-size: 30
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

#table creation script:
#create table snippets (
#id bytea not null,
#load_date timestamp(6),
#piece_of_code text,
#time bigint,
#views bigint,
#primary key (id)
#)